from fpdf import FPDF  # type: ignore
from datetime import datetime
from typing import cast

class KuratorReport(FPDF):
    def header(self):
        # Header with branding
        self.set_font('helvetica', 'B', 12)
        self.set_text_color(41, 121, 255) # accent-blue
        self.cell(0, 10, 'KuratorMind AI', border=False, align='L')
        
        self.set_font('helvetica', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'Forensic Intelligence Report', border=False, align='R')
        self.ln(15)
        
        # Forensic Watermark (Subtle)
        self.set_font('helvetica', 'B', 40)
        self.set_text_color(240, 240, 240)
        self.rotate(45, self.w/2, self.h/2)
        self.text(self.w/4, self.h/2, "DRAFT - FORENSIC USE ONLY")
        self.rotate(0)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by KuratorMind Swarm on {datetime.now().strftime("%Y-%m-%d %H:%M")}', align='C')

    def render_table(self, header, data):
        """Standardised table renderer for creditor lists."""
        self.set_font('helvetica', 'B', 10)
        self.set_fill_color(240, 240, 240)
        self.set_text_color(0, 0, 0)
        
        # Calculate column width
        col_width = (self.w - 2 * self.l_margin) / len(header)
        
        # Header
        for col in header:
            self.cell(col_width, 10, col, border=1, fill=True, align='C')
        self.ln()
        
        # Data
        self.set_font('helvetica', '', 9)
        for row in data:
            for item in row:
                self.cell(col_width, 8, str(item), border=1, align='L')
            self.ln()
        self.ln(5)

def generate_forensic_pdf(title: str, content: str, output_path: str):
    """Generates a professional PDF from Markdown-style content.
    
    Args:
        title: The report title.
        content: The markdown content (simplified support).
        output_path: Where to save the PDF.
    """
    pdf = KuratorReport()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Reset text color for body
    pdf.set_text_color(0, 0, 0)
    
    # Title
    pdf.set_font('helvetica', 'B', 18)
    pdf.multi_cell(0, 12, title, align='L')
    pdf.ln(8)
    
    # Body
    effective_page_width = pdf.w - 2 * pdf.l_margin
    
    # Basic Markdown processing
    lines = content.split('\n')
    i = 0
    while i < len(lines):
        line = str(lines[i]).strip()
        if not line:
            pdf.ln(4)
            i += 1
            continue
        
        # Handle Tables (| col | col |)
        if line.startswith('|') and i + 1 < len(lines) and lines[i+1].strip().startswith('|---'):
            # Extract header
            header = [cell.strip() for cell in line.split('|') if cell.strip()]
            i += 2 # Skip header and separator
            
            # Extract data rows
            data = []
            while i < len(lines) and lines[i].strip().startswith('|'):
                row = [cell.strip() for cell in lines[i].split('|') if cell.strip()]
                if row:
                    data.append(row)
                i += 1
            
            pdf.render_table(header, data)
            continue

        if line.startswith('# '):
            pdf.set_font('helvetica', 'B', 16)
            pdf.set_text_color(41, 121, 255)
            pdf.multi_cell(effective_page_width, 10, line[2:])
            pdf.ln(2)
            pdf.set_font('helvetica', '', 11)
            pdf.set_text_color(0, 0, 0)
        elif line.startswith('## '):
            pdf.set_font('helvetica', 'B', 14)
            pdf.multi_cell(effective_page_width, 8, line[3:])
            pdf.ln(1)
            pdf.set_font('helvetica', '', 11)
        elif line.startswith('### '):
            pdf.set_font('helvetica', 'B', 12)
            pdf.multi_cell(effective_page_width, 7, line[4:])
            pdf.set_font('helvetica', '', 11)
        elif line.startswith('- ') or line.startswith('* '):
            pdf.set_font('helvetica', '', 11)
            pdf.multi_cell(effective_page_width, 6, f"  - {line[2:]}")
        else:
            pdf.set_font('helvetica', '', 11)
            pdf.multi_cell(effective_page_width, 6, line)
            pdf.ln(1)
        
        i += 1
            
    pdf.output(output_path)
    return output_path
